### ISSUE TITLE
启动不了，烦死了

### ISSUE THREAD

**Issue by JxxxxxL** [phith0n/zkar#6]
![image](https://user-images.githubusercontent.com/103913142/167295699-5196a46f-b098-4f58-9945-ae922011859b.png)

**Comment by phith0n** [comment]
你好，请在这里下载编译好的二进制文件使用：<https://github.com/phith0n/zkar/releases/tag/v1.3.0>

**Comment by JxxxxxL** [comment]
我是看了您的安全漫谈，用编译好的应该不能加绕waf的垃圾数据吧?



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月8日(周日) 晚上8:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [phith0n/zkar] 启动不了，烦死了 (Issue #6)




 
你好，请在这里下载编译好的二进制文件使用：https://github.com/phith0n/zkar/releases/tag/v1.3.0

**Comment by phith0n** [comment]
那你需要学习下Golang的基本编译方法。
